### ISSUE TITLE
Erreur de communication avec le serveur ...

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/organigraph#3]
Erreur de communication avec le serveur quand j'ai essayé de mettre des référents et d'ajouter une raison d'être sur SITI !

**Comment by GuillaumeAV** [comment]
Et pareil quand j'essaie de créer un document ...

**Comment by srosset81** [comment]
Tu es connecté ?
Pour l'instant les permissions ne sont pas visibles, contrairement à Archipel.
Je viens de créer une issue pour ça: https://github.com/assemblee-virtuelle/organigraph/issues/5

**Comment by GuillaumeAV** [comment]
Ah non je n'étais pas connecté :) On pourrait cacher les boutons éditer du coup ;)

**Comment by srosset81** [comment]
Ouais c'est l'objet de #5 :)
